// <auto-generated>
//     Generated by tools/verify/localization.py.
//     Lists every language whose sheet is complete; the tool keeps it exact.
// </auto-generated>

using System.Collections.Generic;

namespace Aether.Gameplay.Localization.Tables
{
    /// <summary>Every table this build carries, by language code.</summary>
    internal static class StringsTables
    {
        internal static Dictionary<string, Strings> Build()
        {
            return new Dictionary<string, Strings>
            {
                // English is the reference table, written in MenuStrings.cs and
                // wrapped by StringsEn rather than generated like the others.
                { "en", StringsEn.Table },
                { "es", StringsEs.Table },
                { "de", StringsDe.Table },
                { "fr", StringsFr.Table },
                { "it", StringsIt.Table },
                { "pt", StringsPt.Table },
                { "ru", StringsRu.Table },
                { "tr", StringsTr.Table },
                { "zh", StringsZh.Table },
                { "ja", StringsJa.Table },
                { "fa", StringsFa.Table },
            };
        }
    }
}
